[package]
name = "mpsc-rb"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"
description = "Lock-free multi-producer single-consumer ring buffer"
documentation = "https://docs.rs/mpsc-rb"
homepage = "https://github.com/nthend/mpsc-rb"
repository = "https://github.com/nthend/mpsc-rb.git"
readme = "README.md"
keywords = ["lock-free", "mpsc", "ring-buffer", "rb", "fifo"]
categories = ["concurrency", "data-structures"]
license = "MIT/Apache-2.0"

[dependencies]
